# Generated by Django 3.2.6 on 2021-08-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
